- How do I log into the Youtube account?
- Are the links on this OK?
- Is the date and time OK?  Tuesday is PyAtl Night.
- I  have clarified that the meeting will be first in a series.



Atlanta Functional Programming Meetup

*Take your Python Hyer, Using a Lisp*

WEDNESDAY, 11 November (Dog Day in Japan, because in Japan, dogs say 'wan!', so 11/11 is 'wanwanwanwan!')
7 P.M. EST
Online
Youtube:  https://www.youtube.com/channel/UCYg6qFXDE5SGT_YXhuJPU0A
Hangouts: https://hangouts.google.com/call/J3AJXibg29EbgiNZriH0ACEE

This will be the first of a series of talks about how to use Hy.

*WhyHy?*

The Hy language allows programmers to code in a fully functional language: Hy (of course).

#+NAME: Trying to make a fixed font block
#+BEGIN_SRC python
'Hy is a Lisp that compiles to a valid Python Abstract Syntax Tree, and compiles and runs based on that.'

'Python also       compiles to a valid Python Abstract Syntax Tree, and compiles and runs based on that.'
#+END_SRC


*See that?*

This means that Hy can include Python seamlessly, and Python can include Hy seamlessly.

Hy has all of the advantages of Lisp. Programming in the powerful functional style is the norm. Use of higher-level functions is first nature. *Macros* enable the ultimate in metaprogramming.

This last is incredibly powerful, because it allows coders to write code that writes code; boilerplate can be carefully built, then encapsulated for error-free use by calling macros with only the few variant parameters being specified.

Since Hy can make use of all Python code, the entire, rich ecosystem of Python is available: Numpy, Pandas, Scikit-Learn, Tensor Flow, Keras, networking, gaming...

If you code in Python and want to Learn You Some Lisp, Hy is a great way to do that; one can take a python project and trans-code it in Hy, so learning examples can be as simple or rich as desired.

If you are a Lisper, and would like easy, kludge-free access to the Pythonosphere, dig in!

The first presentation will cover basics, showing how the syntaxes correlate, and how to include Hy in Py, and Py in Hy.

We'd love to see all of you there!

Put this date in your Roam or other media:

7 PM, Wednesday, 11 November 2020
Youtube:  https://www.youtube.com/channel/UCYg6qFXDE5SGT_YXhuJPU0A
Hangouts: https://hangouts.google.com/call/J3AJXibg29EbgiNZriH0ACEE
